### ISSUE TITLE
Missing LICENSE file in the repo of ver 0.1.1

### ISSUE THREAD

**Issue by itsuki-murata** [LinusU/node-random-path#3]
Currently I'm using random-path version 0.1.1, but can't find a LICENSE file in the repo of ver 0.1.1.
Could you add the LICENSE file in the repo of ver 0.1.1?
Thanks in advance.

**Comment by LinusU** [comment]
I've added one here: https://github.com/LinusU/node-random-path/commit/8de412cc08720dff8efe772e5bb4c2d8b0b47c5d

Releases on npm are immutable so I cannot change the already published 0.1.1, but all versions are published under the MIT license.

**Comment by itsuki-murata** [comment]
Thank you for your reply.
That's means I can use the ["8de412c"](https://github.com/LinusU/node-random-path/commit/8de412cc08720dff8efe772e5bb4c2d8b0b47c5d) as the license for ver 0.1.1.
Is my understanding correct?

**Comment by LinusU** [comment]
Yes, all versions are MIT licensed 👍

**Comment by itsuki-murata** [comment]
OK, thank you for reply.
